### ISSUE TITLE
Muss das sein? Die Datenbank setzt das doch automatisch

### ISSUE THREAD

**Issue by CollinAlpert** [xCubeArrow/HotelManagement#1]
https://github.com/xCubeArrow/HotelManagement/blob/84fe40e580307284260c8b4487496ab1ab4dd1e4/customers/src/de/cube/hotel/customers/functions/Utilities.java#L5

**Comment by xCubeArrow** [comment]
Ich möchte gerade nicht mit einer Datenbank arbeiten

**Comment by xCubeArrow** [comment]
Sondern mehr mit vererbung usw.

**Comment by CollinAlpert** [comment]
Ach so, alles klar.
