### ISSUE TITLE
Ist hier Dein einziges Ziel ein SingleRoom anhand einer ID zu bekommen?

### ISSUE THREAD

**Issue by CollinAlpert** [xCubeArrow/HotelManagement#2]
https://github.com/xCubeArrow/HotelManagement/blob/84fe40e580307284260c8b4487496ab1ab4dd1e4/rooms/src/de/cube/hotel/rooms/functions/ManageRooms.java#L20

**Comment by xCubeArrow** [comment]
Jep

**Comment by CollinAlpert** [comment]
Warum verwendest Du dann ein Array? Sowas ist doch viel einfacher: `return singleRooms.stream().filter(singleRoom -> singleRoom.getId() == id).findFirst().orElse(new SingleRoom(0));`

**Comment by xCubeArrow** [comment]
Ich kannte die nicht. Weißt du was? Ich werde einfach beides kombinieren und auch Datenbanken benutzen.

**Comment by CollinAlpert** [comment]
Ach so, alles klar. Du kannst es natürlich auch mit einem Array machen, das sieht nur etwas komisch aus.
