### ISSUE TITLE
Hier kann man einen Stream benutzen, muss man aber nicht.

### ISSUE THREAD

**Issue by CollinAlpert** [xCubeArrow/HotelManagement#3]
https://github.com/xCubeArrow/HotelManagement/blob/84fe40e580307284260c8b4487496ab1ab4dd1e4/rooms/src/de/cube/hotel/rooms/functions/ManageRooms.java#L57

`singleRooms.removeIf(BaseRoom::hasChanged).forEach(singleRoom -> {`

Nur, damit Du weißt, dass ein Stream nicht das einzig Wahre ist. ArrayLists können auch manchmal die Sachen, die Du brauchst.

**Comment by xCubeArrow** [comment]
Das ist ja cool, danke

**Comment by CollinAlpert** [comment]
Yup
